services:
  - type: web
    name: twilio-voice-gpt4o
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: VOICE_ID
        sync: false
      - key: BASE_URL
        sync: false
      - key: PORT
